Repository HarshKumarraghav/periodically_webapp, pull requests merged in 2022-10, with the labels that each got.

#31 Made correction In Readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#35 readme update 🔖
  README.md
Labels: hacktoberfest-accepted

#39 Updated history page
  assets/History/History.md
  assets/History/assets/mendeleev periodic table.jpg
  assets/History/assets/mendeleev.jfif
Labels: hacktoberfest, hacktoberfest-accepted

#46 folder name change(periodic table)
  components/ExploreData.js
  components/Header.js
  components/Periodic_Table/AtomElement.module.css
  components/Periodic_Table/Elements.js
  components/Periodic_Table/FilterbyCategory.js
  components/Periodic_Table/PeriodicDetail.js
  components/RandomInfo.js
  pages/elementdata/[elementdata].js
  pages/periodictable.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
